### ISSUE TITLE
bug css sur le logo des chaines

### ISSUE THREAD

**Issue by newtomsoft** [javascriptdezero/ressources-dev-web#3]
salut
il y a un petit bug de css sur les logos des chaines youtubes 

voir la vidéo :
[![voir vidéo](https://img.youtube.com/vi/UMk444jX02k/maxresdefault.jpg)](https://youtu.be/UMk444jX02k)

**Comment by javascriptdezero** [comment]
Je n'ai jamais trouvé la cause de ce bug. Mais ça ne le fait plus donc je pense que c'était un bug mineur dans le navigateur.
